name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build
      env:
        API_KEY: ${{ secrets.WEBHOOK }}
      run: |
        # Replace placeholders in your HTML with actual secrets
        sed -i 's/{{WEBHOOK}}/'$WEBHOOK'/g' index.html
              env:
        API_KEY: ${{ secrets.BIN_NAME }}
      run: |
        # Replace placeholders in your HTML with actual secrets
        sed -i 's/{{BIN__NAME}}/'$BIN_NAME'/g' index.html
              env:
        API_KEY: ${{ secrets.MASTERKEY }}
      run: |
        # Replace placeholders in your HTML with actual secrets
        sed -i 's/{{MASTERKEY}}/'$MASTERKEY'/g' index.html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
