name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Inject Secrets into HTML
      run: |
        echo "Injecting secrets into HTML"
        sed -i 's|{{WEBHOOK}}|${{ secrets.WEBHOOK }}|g' -. ---/index.html
        sed -i 's|{{MASTERKEY}|${{ secrets.MASTERKEY }}|g' -. ---/index.html
        sed -i 's|{BIN_NAME}|${{ secrets.BIN_NAME }}|g' -. ---/index.html

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -. ---/index.html
        git commit -m "Inject secrets into HTML"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
